### PR TITLE
LPS-73924 buildLang

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest

**Comment by vicnate5** [comment]
Test fixes sent to master
https://github.com/brianchandotcom/liferay-portal/pull/50890

After this is merge I will add the toggle and resend this pull.

**Comment by brandizzi** [comment]
Hey @vicnate5! Do I need to do something else regarding this pull request?

Thanks!

**Comment by vicnate5** [comment]
@brandizzi Closing this pull. This is continued on https://github.com/liferay/com-liferay-portal-workflow/pull/121

**Pull request closed without merging**
